---

- name: Install ruby
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        update_cache: yes
        name:
          - git
          - ruby-full
          - ruby-bundler
          - build-essential
